"""change user to use strings

Revision ID: 0522a46321b7
Revises: 52c0fdb0f0b2
Create Date: 2025-01-13 16:21:49.850733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0522a46321b7"
down_revision: Union[str, None] = "52c0fdb0f0b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "events_user_fkey",
        "events",
        schema="lost",
    )
    op.drop_table(
        "users",
        schema="lost",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("age", sa.String(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("nav_skill", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["position"], ["lost.positions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="lost",
        if_not_exists=True,
    )
    op.create_foreign_key(
        "events_user_fkey",
        "events",
        "users",
        local_cols=["user"],
        remote_cols=["id"],
        source_schema="lost",
        referent_schema="lost",
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users", schema="lost")
    # ### end Alembic commands ###
