"""change short strings to text

Revision ID: 7a590ddcf37e
Revises: 0522a46321b7
Create Date: 2025-01-15 10:35:00.108212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7a590ddcf37e"
down_revision: Union[str, None] = "0522a46321b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("age", sa.String(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("nav_skill", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["position"], ["lost.positions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="lost",
        if_not_exists=True,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("when", sa.Text(), nullable=True),
        sa.Column("time_of_day", sa.Text(), nullable=True),
        sa.Column("day_of_week", sa.Text(), nullable=True),
        sa.Column("guidance", sa.Text(), nullable=True),
        sa.Column("group", sa.Text(), nullable=True),
        sa.Column("factors", sa.Text(), nullable=True),
        sa.Column("familiarity", sa.Integer(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("explain", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["position"], ["lost.positions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user"], ["lost.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="lost",
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events", schema="lost")
    op.drop_table("users", schema="lost")
    op.drop_geospatial_index(
        "idx_positions_start",
        table_name="positions",
        schema="lost",
        postgresql_using="gist",
        column_name="start",
    )
    op.drop_geospatial_index(
        "idx_positions_lost",
        table_name="positions",
        schema="lost",
        postgresql_using="gist",
        column_name="lost",
    )
    op.drop_geospatial_index(
        "idx_positions_end", table_name="positions", schema="lost", postgresql_using="gist", column_name="end"
    )
    op.drop_geospatial_table("positions", schema="lost")
    # ### end Alembic commands ###
